from typing import Protocol, Optional
from domain.auth.user import User

class UserRepository(Protocol):
    def get_by_username(self, username: str) -> Optional[User]: ...
    def get_by_id(self, user_id: int) -> Optional[User]: ...
